packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'examples/*'
  - '!examples/hydra-vue-f7'
  - '!examples/hydra-nextjs'
  - '!examples/nuxt-blog-starter'
  - 'docs/examples/test-react'
  - 'docs/examples/test-svelte'
  - 'docs/examples/test-vue'
