[build]
  command = "pnpm run build"
  publish = ".next"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors https://hydra.pretagov.com https://*.pretagov.com http://localhost:*"
