import type { TestInfo } from '@playwright/test';

/**
 * An unmet ENVIRONMENT precondition skips locally and FAILS on CI.
 *
 * Locally these frontends and discovery files are opt-in: you run one project at
 * a time and the others aren't up, so skipping is what lets `--project=mock`
 * work on a laptop. On CI every one of them is started or generated by the
 * workflow, so "it isn't there" doesn't mean "not applicable" — it means the
 * workflow broke. Skipping then reports a green run that tested nothing, which
 * is the one failure mode CI cannot afford: block-sanity had stopped running
 * entirely in the nextjs job (no DISCOVER_BLOCKS_API in its env) and said
 * "3 skipped" while the job went green.
 *
 * For ENVIRONMENT preconditions only. A deliberate scope rule — "this spec only
 * applies to mock/nuxt/nextjs" — stays an ordinary skip, because nothing is
 * broken and no CI change could make that test run.
 *
 * @param testInfo - the running test's info (for the local skip)
 * @param met - is the precondition satisfied
 * @param reason - what is missing, phrased so a CI failure names the fix
 */
export function requireEnvironment(
  testInfo: TestInfo,
  met: boolean,
  reason: string,
): void {
  if (met) return;
  if (process.env.CI) {
    throw new Error(
      `Environment precondition not met on CI: ${reason}. ` +
        `On CI this is a workflow fault, not a reason to skip — the tests it ` +
        `guards would silently not run.`,
    );
  }
  testInfo.skip(true, reason);
}
